[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gillespie_algorithm"
version = "0.1"
dependencies = ["numpy","scipy","matplotlib"]
[tool.hatch.build.targets.wheel]
packages = ["gillespie_algorithm"]
